---
title: "Graphical Convolutional Networks"
output: 
  html_document:
    toc: FALSE
title-block-banner: "#FFCC00"
engine: knitr 
cv:
  pdf: "gcn_pres.pdf"
---
# Graphical Convolutional Networks

I collaborated alongside a peer on a final project in STAT 4270: Network Data Analysis and Graphical Models. Together, we investigated the application of different sampling techniques for semi-supervised classification on Graph Attention Networks (GATs). Utilizing citation network data, we trained the GAT models and selected GraphSAGE, GraphSAINT, and ClusterGCN sampling methods for node dropout. We calculated the classification accuracy over four trials and found that these sampling techniques matched or, in some cases, exceeded the baseline model performance afforded by the GAT. This project aimed to apply techniques from cutting-edge network models and deep learning literature and sought to improve existing techniques; I was drawn to this problem because of the increased prevalence and importance of graphical data analysis for classification and prediction models.

```{css, echo=FALSE}
#title-block-header .description {
    display: none;
}
```

```{css echo=FALSE}
.embed-container {
    position: relative;
    padding-bottom: 129%;
    height: 0;
    overflow: hidden;
    max-width: 100%;
}

.embed-container iframe,
.embed-container object,
.embed-container embed {
    position: absolute;
    top: 0;
    left: 0;
    width: 100%;
    height: 100%;
}
```

```{=html}
<p class="text-center">
  <a class="btn btn-primary btn-lg cv-download" href="`r rmarkdown::metadata$cv$pdf`" target="_blank">
    <i class="fa-solid fa-file-arrow-down"></i>&ensp;Download Presentation
  </a>
</p>

<div class="embed-container">
  <iframe src="`r rmarkdown::metadata$cv$pdf`" style="border: 0.5px"></iframe>
</div>
```

