---
title: "Time Series Analysis - COVID-19 Vaccine Uptake"
output: 
  html_document:
    toc: FALSE
title-block-banner: "#3399FF"
engine: knitr 
cv:
  pdf: "ts_project.pdf"
---
# A Time Series Analysis of COVID-19 Vaccine Uptake in Georgia

I collaborated with another student to investigate trends in COVID-19 vaccine uptake and compare the performance of different ARIMA models for a STAT 4280 final project. We transformed The raw cumulative data obtained from the CDC to recover the number of vaccines administered daily and then averaged by week. Linear model residuals demonstrated nonstationarity, so the data required further smoothing on a log scale. ARMA(1,1) and ARMA(1,2) models were then fit using a nonparametric loess regression; the ARMA(1,2) model resulted in better performance over the former. The end goal of this project was to investigate vaccine uptake and develop a model that could forecast the number of vaccines required by the Department of Public Health in Georgia.

```{css, echo=FALSE}
#title-block-header .description {
    display: none;
}
```

```{css echo=FALSE}
.embed-container {
    position: relative;
    padding-bottom: 129%;
    height: 0;
    overflow: hidden;
    max-width: 100%;
}

.embed-container iframe,
.embed-container object,
.embed-container embed {
    position: absolute;
    top: 0;
    left: 0;
    width: 100%;
    height: 100%;
}
```

```{=html}
<p class="text-center">
  <a class="btn btn-primary btn-lg cv-download" href="`r rmarkdown::metadata$cv$pdf`" target="_blank">
    <i class="fa-solid fa-file-arrow-down"></i>&ensp;Download Report
  </a>
</p>

<div class="embed-container">
  <iframe src="`r rmarkdown::metadata$cv$pdf`" style="border: 0.5px"></iframe>
</div>
```

